-- Mean-pooled vanilla CodeBERT vectors are anisotropic. In production data,
-- unrelated Godot projects reached cosine similarity 0.9985, so these derived
-- flags are unsafe for moderation/dispute decisions.
--
-- Preserve source snapshots and AI review reports. Only invalidate the
-- reproducible plagiarism artifacts generated by the retired algorithm, then
-- mark affected snapshots pending so an admin trigger can rebuild them with
-- the v2 structural fingerprint.
UPDATE public.source_snapshots snapshot
SET plagiarism_status = 'pending',
    plagiarism_error = NULL,
    plagiarism_completed_at = NULL
WHERE EXISTS (
    SELECT 1
    FROM public.code_embeddings embedding
    WHERE embedding.source_snapshot_id = snapshot.id
      AND embedding.model_name = 'microsoft/codebert-base'
);

DELETE FROM public.plagiarism_flags
WHERE model_name = 'microsoft/codebert-base';

DELETE FROM public.code_embeddings
WHERE model_name = 'microsoft/codebert-base';

COMMENT ON COLUMN public.code_embeddings.model_name IS
    'Versioned source fingerprint algorithm; current default is godotlaunch/structural-code-fingerprint';
